///////////////////////////////////////////////////////////////////////////////
//
// $Id: IfStatement.java 1 2007-12-12 17:37:26Z t-scheller $
// 
// created by: Christoph Müller
// created at: 24.02.2007 17:30:00
//
///////////////////////////////////////////////////////////////////////////////

//
// Generated by JTB 1.3.2
//

package org.gbt2.instrumentation.java15.syntaxtree;

import java.io.IOException;

import org.gbt2.instrumentation.java15.visitor.GJNoArguVisitor;
import org.gbt2.instrumentation.java15.visitor.GJVisitor;
import org.gbt2.instrumentation.java15.visitor.GJVoidVisitor;
import org.gbt2.instrumentation.java15.visitor.Visitor;
import org.gbt2.instrumentation.java15.visitor.VisitorWithException;

/**
 * Grammar production:
 * 
 * <PRE>
 * 
 * f0 -> "if"
 * f1 -> "("
 * f2 -> Expression()
 * f3 -> ")"
 * f4 -> Statement()
 * f5 -> [ "else" Statement() ]
 * 
 * </PRE>
 */
public class IfStatement implements Node {
    private Node parent;

    public NodeToken f0;

    public NodeToken f1;

    public Expression f2;

    public NodeToken f3;

    public Statement f4;

    public NodeOptional f5;

    public IfStatement(NodeToken n0, NodeToken n1, Expression n2, NodeToken n3,
            Statement n4, NodeOptional n5) {
        f0 = n0;
        if (f0 != null)
            f0.setParent(this);
        f1 = n1;
        if (f1 != null)
            f1.setParent(this);
        f2 = n2;
        if (f2 != null)
            f2.setParent(this);
        f3 = n3;
        if (f3 != null)
            f3.setParent(this);
        f4 = n4;
        if (f4 != null)
            f4.setParent(this);
        f5 = n5;
        if (f5 != null)
            f5.setParent(this);
    }

    public IfStatement(Expression n0, Statement n1, NodeOptional n2) {
        f0 = new NodeToken("if");
        if (f0 != null)
            f0.setParent(this);
        f1 = new NodeToken("(");
        if (f1 != null)
            f1.setParent(this);
        f2 = n0;
        if (f2 != null)
            f2.setParent(this);
        f3 = new NodeToken(")");
        if (f3 != null)
            f3.setParent(this);
        f4 = n1;
        if (f4 != null)
            f4.setParent(this);
        f5 = n2;
        if (f5 != null)
            f5.setParent(this);
    }

    public void accept(VisitorWithException v) throws IOException {
        v.visit(this);
    }

    public void accept(Visitor v) {
        v.visit(this);
    }

    public <R, A> R accept(GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    public <R> R accept(GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    public <A> void accept(GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }

    public void setParent(Node n) {
        parent = n;
    }

    public Node getParent() {
        return parent;
    }
}
