/******************************************************************************
 * Copyright (c) 2007 Stefan Franke, Robert Hanussek, Benjamin Keil,          *
 *                    Steffen Kieß, Johannes Langauf,                         *
 *                    Christoph Marian Müller, Igor Podolskiy,                *
 *                    Tilmann Scheller, Michael Starzmann, Markus Wittlinger  *
 * All rights reserved. This program and the accompanying materials           *
 * are made available under the terms of the Eclipse Public License v1.0      *
 * which accompanies this distribution, and is available at                   *
 * http://www.eclipse.org/legal/epl-v10.html                                  *
 ******************************************************************************/

/* Generated By:JavaCC: Do not edit this line. CoverageLogParserConstants.java */
package org.codecover.instrumentation.measurement.parser;

@SuppressWarnings("all")
public interface CoverageLogParserConstants {

    int EOF = 0;

    int COMMENT = 1;

    int SPACECHAR = 2;

    int EOL = 3;

    int END_TEST_CASE = 4;

    int HYPHEN = 5;

    int TEST_SESSION_CONTAINER = 6;

    int START_TEST_CASE = 7;

    int START_SECTION = 8;

    int COUNTER_LITERAL = 9;

    int INTEGER_LITERAL = 10;

    int STRING_LITERAL = 11;

    int DEFAULT = 0;

    String[] tokenImage = { "<EOF>", "<COMMENT>", "\" \"", "<EOL>",
            "\"END_TEST_CASE\"", "\"-\"", "\"TEST_SESSION_CONTAINER\"",
            "\"START_TEST_CASE\"", "\"START_SECTION\"", "<COUNTER_LITERAL>",
            "<INTEGER_LITERAL>", "<STRING_LITERAL>", };

}
