/* Generated By:JavaCC: Do not edit this line. XampilParserConstants.java */
package org.codecover.instrumentation.xampil.parser;

public interface XampilParserConstants {

  int EOF = 0;
  int SPACE_CHAR = 1;
  int SINGLE_LINE_COMMENT = 2;
  int EOL = 3;
  int DECLARATION = 4;
  int PROGRAM = 5;
  int ENDPROGRAM = 6;
  int BOOLEAN = 7;
  int INTEGER = 8;
  int STRING = 9;
  int IF = 10;
  int THEN = 11;
  int ELSE = 12;
  int ENDIF = 13;
  int WHILE = 14;
  int DO = 15;
  int ENDWHILE = 16;
  int SWITCH = 17;
  int CASE = 18;
  int CASE_DEFAULT = 19;
  int ENDCASE = 20;
  int ENDSWITCH = 21;
  int FILE = 22;
  int OVERWRITE = 23;
  int APPEND = 24;
  int AND = 25;
  int OR = 26;
  int NOT = 27;
  int TRUE = 28;
  int FALSE = 29;
  int LPAREN = 30;
  int RPAREN = 31;
  int COLON = 32;
  int ASSIGN = 33;
  int EQ = 34;
  int NEQ = 35;
  int LT = 36;
  int GT = 37;
  int LE = 38;
  int GE = 39;
  int PLUS = 40;
  int MINUS = 41;
  int STAR = 42;
  int SLASH = 43;
  int IDENTIFIER = 44;
  int INTEGER_LITERAL = 45;
  int STRING_LITERAL = 46;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<SPACE_CHAR>",
    "<SINGLE_LINE_COMMENT>",
    "<EOL>",
    "\"DECLARATION\"",
    "\"PROGRAM\"",
    "\"ENDPROGRAM\"",
    "\"BOOLEAN\"",
    "\"INTEGER\"",
    "\"STRING\"",
    "\"IF\"",
    "\"THEN\"",
    "\"ELSE\"",
    "\"ENDIF\"",
    "\"WHILE\"",
    "\"DO\"",
    "\"ENDWHILE\"",
    "\"SWITCH\"",
    "\"CASE\"",
    "\"DEFAULT\"",
    "\"ENDCASE\"",
    "\"ENDSWITCH\"",
    "\"FILE\"",
    "\"OVERWRITE\"",
    "\"APPEND\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\":=\"",
    "\"=\"",
    "\"<>\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<IDENTIFIER>",
    "<INTEGER_LITERAL>",
    "<STRING_LITERAL>",
  };

}
