///////////////////////////////////////////////////////////////////////////////
//
// $Id: SQLSelectSimple.java 1 2007-12-12 17:37:26Z t-scheller $
// 
///////////////////////////////////////////////////////////////////////////////

//
// Generated by JTB 1.3.2
//

package org.gbt2.instrumentation.cobol85.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> &lt;SELECT&gt;
 * f1 -> [ &lt;DISTINCT&gt; ]
 * f2 -> ( SQLIdentifier() )+
 * f3 -> [ &lt;INTO&gt; ( SQLParameter() )+ ]
 * f4 -> SQLSelectFrom()
 * f5 -> [ SQLSelectInnerJoin() ]
 * f6 -> [ SQLSelectWhere() ]
 * f7 -> [ SQLSelectGroupBy() ]
 * f8 -> [ SQLSelectHaving() ]
 * f9 -> [ SQLSelectOrderBy() ]
 * f10 -> [ SQLSelectForUpdate() ]
 * f11 -> [ &lt;FOR&gt; &lt;FETCH&gt; &lt;ONLY&gt; ]
 * f12 -> [ &lt;WITH&gt; SQLIdentifier() ]
 * </PRE>
 */
public class SQLSelectSimple implements Node {
   private Node parent;
   public NodeToken f0;
   public NodeOptional f1;
   public NodeList f2;
   public NodeOptional f3;
   public SQLSelectFrom f4;
   public NodeOptional f5;
   public NodeOptional f6;
   public NodeOptional f7;
   public NodeOptional f8;
   public NodeOptional f9;
   public NodeOptional f10;
   public NodeOptional f11;
   public NodeOptional f12;

   public SQLSelectSimple(NodeToken n0, NodeOptional n1, NodeList n2, NodeOptional n3, SQLSelectFrom n4, NodeOptional n5, NodeOptional n6, NodeOptional n7, NodeOptional n8, NodeOptional n9, NodeOptional n10, NodeOptional n11, NodeOptional n12) {
      f0 = n0;
      if ( f0 != null ) f0.setParent(this);
      f1 = n1;
      if ( f1 != null ) f1.setParent(this);
      f2 = n2;
      if ( f2 != null ) f2.setParent(this);
      f3 = n3;
      if ( f3 != null ) f3.setParent(this);
      f4 = n4;
      if ( f4 != null ) f4.setParent(this);
      f5 = n5;
      if ( f5 != null ) f5.setParent(this);
      f6 = n6;
      if ( f6 != null ) f6.setParent(this);
      f7 = n7;
      if ( f7 != null ) f7.setParent(this);
      f8 = n8;
      if ( f8 != null ) f8.setParent(this);
      f9 = n9;
      if ( f9 != null ) f9.setParent(this);
      f10 = n10;
      if ( f10 != null ) f10.setParent(this);
      f11 = n11;
      if ( f11 != null ) f11.setParent(this);
      f12 = n12;
      if ( f12 != null ) f12.setParent(this);
   }

   public SQLSelectSimple(NodeOptional n0, NodeList n1, NodeOptional n2, SQLSelectFrom n3, NodeOptional n4, NodeOptional n5, NodeOptional n6, NodeOptional n7, NodeOptional n8, NodeOptional n9, NodeOptional n10, NodeOptional n11) {
      f0 = new NodeToken("select");
      if ( f0 != null ) f0.setParent(this);
      f1 = n0;
      if ( f1 != null ) f1.setParent(this);
      f2 = n1;
      if ( f2 != null ) f2.setParent(this);
      f3 = n2;
      if ( f3 != null ) f3.setParent(this);
      f4 = n3;
      if ( f4 != null ) f4.setParent(this);
      f5 = n4;
      if ( f5 != null ) f5.setParent(this);
      f6 = n5;
      if ( f6 != null ) f6.setParent(this);
      f7 = n6;
      if ( f7 != null ) f7.setParent(this);
      f8 = n7;
      if ( f8 != null ) f8.setParent(this);
      f9 = n8;
      if ( f9 != null ) f9.setParent(this);
      f10 = n9;
      if ( f10 != null ) f10.setParent(this);
      f11 = n10;
      if ( f11 != null ) f11.setParent(this);
      f12 = n11;
      if ( f12 != null ) f12.setParent(this);
   }

   public void accept(org.gbt2.instrumentation.cobol85.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(org.gbt2.instrumentation.cobol85.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(org.gbt2.instrumentation.cobol85.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(org.gbt2.instrumentation.cobol85.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

