//
// Generated by JTB 1.3.2
//

package org.codecover.instrumentation.c.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * declarationSpecifiers -> DeclarationSpecifiers()
 * nodeChoice -> ( Declarator() | [ AbstractDeclarator() ] )
 * </PRE>
 */
public class ParameterDeclaration extends org.codecover.instrumentation.c.adapter.CCNode implements Node {
   private Node parent;
   public DeclarationSpecifiers declarationSpecifiers;
   public NodeChoice nodeChoice;

   public ParameterDeclaration(DeclarationSpecifiers n0, NodeChoice n1) {
      declarationSpecifiers = n0;
      if ( declarationSpecifiers != null ) declarationSpecifiers.setParent(this);
      nodeChoice = n1;
      if ( nodeChoice != null ) nodeChoice.setParent(this);
   }

   public void accept(org.codecover.instrumentation.c.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(org.codecover.instrumentation.c.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(org.codecover.instrumentation.c.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(org.codecover.instrumentation.c.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

