//
// Generated by JTB 1.3.2
//

package org.codecover.instrumentation.cobol85.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> &lt;DELETE&gt;
 * f1 -> &lt;FROM&gt;
 * f2 -> SQLIdentifier()
 * f3 -> [ SQLIdentifier() ]
 * f4 -> [ SQLSelectWhere() ]
 * </PRE>
 */
public class ExecSQLStatementDelete implements Node {
   private Node parent;
   public NodeToken f0;
   public NodeToken f1;
   public SQLIdentifier f2;
   public NodeOptional f3;
   public NodeOptional f4;

   public ExecSQLStatementDelete(NodeToken n0, NodeToken n1, SQLIdentifier n2, NodeOptional n3, NodeOptional n4) {
      f0 = n0;
      if ( f0 != null ) f0.setParent(this);
      f1 = n1;
      if ( f1 != null ) f1.setParent(this);
      f2 = n2;
      if ( f2 != null ) f2.setParent(this);
      f3 = n3;
      if ( f3 != null ) f3.setParent(this);
      f4 = n4;
      if ( f4 != null ) f4.setParent(this);
   }

   public ExecSQLStatementDelete(SQLIdentifier n0, NodeOptional n1, NodeOptional n2) {
      f0 = new NodeToken("delete");
      if ( f0 != null ) f0.setParent(this);
      f1 = new NodeToken("from");
      if ( f1 != null ) f1.setParent(this);
      f2 = n0;
      if ( f2 != null ) f2.setParent(this);
      f3 = n1;
      if ( f3 != null ) f3.setParent(this);
      f4 = n2;
      if ( f4 != null ) f4.setParent(this);
   }

   public void accept(org.codecover.instrumentation.cobol85.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(org.codecover.instrumentation.cobol85.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(org.codecover.instrumentation.cobol85.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(org.codecover.instrumentation.cobol85.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

