//
// Generated by JTB 1.3.2
//

package org.codecover.instrumentation.cobol85.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> &lt;WHENEVER&gt;
 * f1 -> ( &lt;NOT&gt; &lt;FOUND&gt; &lt;CONTINUE&gt; | ( &lt;SQLWARNING&gt; | &lt;SQLERROR&gt; ) &lt;GO&gt; &lt;TO&gt; CobolWord() )
 * </PRE>
 */
public class ExecSQLStatementWhenever implements Node {
   private Node parent;
   public NodeToken f0;
   public NodeChoice f1;

   public ExecSQLStatementWhenever(NodeToken n0, NodeChoice n1) {
      f0 = n0;
      if ( f0 != null ) f0.setParent(this);
      f1 = n1;
      if ( f1 != null ) f1.setParent(this);
   }

   public ExecSQLStatementWhenever(NodeChoice n0) {
      f0 = new NodeToken("whenever");
      if ( f0 != null ) f0.setParent(this);
      f1 = n0;
      if ( f1 != null ) f1.setParent(this);
   }

   public void accept(org.codecover.instrumentation.cobol85.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(org.codecover.instrumentation.cobol85.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(org.codecover.instrumentation.cobol85.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(org.codecover.instrumentation.cobol85.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

