//
// Generated by JTB 1.3.2
//

package org.codecover.instrumentation.cobol85.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> &lt;ZERO&gt;
 *       | &lt;ZEROS&gt;
 *       | &lt;ZEROES&gt;
 *       | &lt;SPACE&gt;
 *       | &lt;SPACES&gt;
 *       | &lt;HIGH_VALUE&gt;
 *       | &lt;HIGH_VALUES&gt;
 *       | &lt;LOW_VALUE&gt;
 *       | &lt;LOW_VALUES&gt;
 *       | &lt;QUOTE&gt;
 *       | &lt;QUOTES&gt;
 *       | &lt;NULL&gt;
 *       | &lt;NULLS&gt;
 * </PRE>
 */
public class FigurativeConstant implements Node {
   private Node parent;
   public NodeChoice f0;

   public FigurativeConstant(NodeChoice n0) {
      f0 = n0;
      if ( f0 != null ) f0.setParent(this);
   }

   public void accept(org.codecover.instrumentation.cobol85.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(org.codecover.instrumentation.cobol85.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(org.codecover.instrumentation.cobol85.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(org.codecover.instrumentation.cobol85.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

