//
// Generated by JTB 1.3.2
//

package org.codecover.instrumentation.cobol85.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> &lt;GROUP&gt;
 * f1 -> &lt;BY&gt;
 * f2 -> ( SQLIdentifier() [ &lt;COMMACHAR&gt; ] )+
 * </PRE>
 */
public class SQLSelectGroupBy implements Node {
   private Node parent;
   public NodeToken f0;
   public NodeToken f1;
   public NodeList f2;

   public SQLSelectGroupBy(NodeToken n0, NodeToken n1, NodeList n2) {
      f0 = n0;
      if ( f0 != null ) f0.setParent(this);
      f1 = n1;
      if ( f1 != null ) f1.setParent(this);
      f2 = n2;
      if ( f2 != null ) f2.setParent(this);
   }

   public SQLSelectGroupBy(NodeList n0) {
      f0 = new NodeToken("group");
      if ( f0 != null ) f0.setParent(this);
      f1 = new NodeToken("by");
      if ( f1 != null ) f1.setParent(this);
      f2 = n0;
      if ( f2 != null ) f2.setParent(this);
   }

   public void accept(org.codecover.instrumentation.cobol85.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(org.codecover.instrumentation.cobol85.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(org.codecover.instrumentation.cobol85.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(org.codecover.instrumentation.cobol85.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

